# Include user config (generated by setup.sh)
-include config.mk

# Verificar que PIN_ROOT existe
ifndef PIN_ROOT
$(error PIN_ROOT not set. Run ./setup.sh first)
endif

# Verificar que el directorio existe
ifeq ($(wildcard $(PIN_ROOT)),)
$(error PIN_ROOT=$(PIN_ROOT) does not exist. Run ./setup.sh)
endif

CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
include $(CONFIG_ROOT)/makefile.config

# Directorios
SRC_DIR := src
OBJ_DIR := obj-$(TARGET)
PROFILER_DIR := $(SRC_DIR)/profiler
INJECTOR_DIR := $(SRC_DIR)/injector
COMMON_DIR := $(SRC_DIR)/common

# Flags adicionales
TOOL_CXXFLAGS += -I$(COMMON_DIR) -std=c++17 -Wall -Wextra
# Targets
PROFILER_TOOLS := ProfilerBasic ProfilerByFunction ProfilerTargeted
INJECTOR_TOOLS := FaultInjector

ALL_TOOLS := $(PROFILER_TOOLS) $(INJECTOR_TOOLS)

.PHONY: all clean profilers injectors tests

all: profilers injectors

profilers: $(PROFILER_TOOLS)

injectors: $(INJECTOR_TOOLS)

# Reglas para profilers
ProfilerBasic: $(OBJ_DIR)/ProfilerBasic.so
ProfilerByFunction: $(OBJ_DIR)/ProfilerByFunction.so
ProfilerTargeted: $(OBJ_DIR)/ProfilerTargeted.so

# Reglas para injector
FaultInjector: $(OBJ_DIR)/FaultInjector.so

# Pattern rule para compilar .cpp a .so
$(OBJ_DIR)/Profiler%.so: $(PROFILER_DIR)/Profiler%.cpp | $(OBJ_DIR)
	$(CXX) $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $< $(TOOL_LDFLAGS_NOOPT) $(TOOL_LPATHS) $(TOOL_LIBS)

$(OBJ_DIR)/FaultInjector.so: $(INJECTOR_DIR)/FaultInjector.cpp | $(OBJ_DIR)
	$(CXX) $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $< $(TOOL_LDFLAGS_NOOPT) $(TOOL_LPATHS) $(TOOL_LIBS)

$(OBJ_DIR):
	mkdir -p $(OBJ_DIR)

# Tests
tests:
	$(MAKE) -C tests

clean:
	rm -rf $(OBJ_DIR)
	$(MAKE) -C tests clean

# Helper: mostrar configuración
info:
	@echo "PIN_ROOT: $(PIN_ROOT)"
	@echo "TARGET: $(TARGET)"
	@echo "OBJ_DIR: $(OBJ_DIR)"
	@echo "Tools: $(ALL_TOOLS)"
