#!/bin/bash
set -e

PIN_VERSION="external-4.0-99633-g5ca9893f2-gcc-linux"
PIN_URL="https://software.intel.com/sites/landingpage/pintool/downloads/pin-${PIN_VERSION}.tar.gz"
PIN_DIR="pin-${PIN_VERSION}"

if [ -d "$PIN_DIR" ]; then
    echo "[INFO] Pin already downloaded at $PIN_DIR"
    exit 0
fi

echo "[INFO] Downloading Intel Pin ${PIN_VERSION}..."
wget -q --show-progress "$PIN_URL" -O pin.tar.gz

echo "[INFO] Extracting..."
tar xzf pin.tar.gz
rm pin.tar.gz


echo "[INFO] Pin installed at $PIN_DIR"
echo "[INFO] Creating config.mk..."

mv pin-${PIN_VERSION} pin
cat > config.mk <<EOF
# Auto-generated by setup.sh
PIN_ROOT := \$(shell pwd)/pin
EOF

echo "[DONE] Run 'make' to build pintools"
